telegram_token = ""
telegram_chat_id = ""

aws_ip_node_list = []
aws_ip_sync_list = []
aws_ip_send_list = []

chain_param_interval = 3000
chain_param_poolsize = 200000
chain_param_timeout_gap = 999999
chain_param_cycles_limit = 630000000
chain_param_tx_num_limit = 30000
